// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUfDNWTUJom3XnlD247VAydTjDkzJhut8',
    appId: '1:1022654707841:web:35e2c73d74cb30de503580',
    messagingSenderId: '1022654707841',
    projectId: 'chatapp-d0cb9',
    authDomain: 'chatapp-d0cb9.firebaseapp.com',
    storageBucket: 'chatapp-d0cb9.firebasestorage.app',
    measurementId: 'G-CZFBBD84CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA69Af0pVwwtMNkZo5jGEWk4jczvH6q2Ng',
    appId: '1:1022654707841:android:76b619eab9cc5700503580',
    messagingSenderId: '1022654707841',
    projectId: 'chatapp-d0cb9',
    storageBucket: 'chatapp-d0cb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI4AxPuzB7STbRLAeRf68V_4vxnt0eps4',
    appId: '1:1022654707841:ios:f22b799bdc649c52503580',
    messagingSenderId: '1022654707841',
    projectId: 'chatapp-d0cb9',
    storageBucket: 'chatapp-d0cb9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI4AxPuzB7STbRLAeRf68V_4vxnt0eps4',
    appId: '1:1022654707841:ios:f22b799bdc649c52503580',
    messagingSenderId: '1022654707841',
    projectId: 'chatapp-d0cb9',
    storageBucket: 'chatapp-d0cb9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUfDNWTUJom3XnlD247VAydTjDkzJhut8',
    appId: '1:1022654707841:web:913c33b2d5564ffc503580',
    messagingSenderId: '1022654707841',
    projectId: 'chatapp-d0cb9',
    authDomain: 'chatapp-d0cb9.firebaseapp.com',
    storageBucket: 'chatapp-d0cb9.firebasestorage.app',
    measurementId: 'G-BHGG73DLL7',
  );
}
